language: python
python:
  - "3.5"
install:
  - pip install requests
# command to run tests

version: 2.1
jobs:
  test:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt || true
      - run:
          name: Run unit tests
          command: python -m unittest discover -s tests -p "*_test.py"
          working_directory: ./  # add this line
workflows:
  version: 2.1
  test:
    jobs:
      - test
