version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install requests
          command: |
            pip install requests

      - run:
          name: Run tests
          command: |
            pytest --junitxml=test-results/junit.xml UNITTESTRC.py
