version: 2.1
jobs:
  test:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command:
          pip install pytest
          pip install requests
          pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: python -m unittest discover -s tests -p "UNITTESTRC.py"
workflows:
  version: 2.1
  test:
    jobs:
      - test
